### ISSUE TITLE
[Bug]: bad link in readme

### ISSUE THREAD

**Issue by aldenc** [openresearchcalendar/openresearchcalendar.github.io#102]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Contact Details

aconner@turing.ac.uk

### What happened? / Describe the bug

the link in the readme TOC for "re-use and licensing" doesn't work

### Environment (if relevant)

```Markdown
- OS:
- Browser:
- Version:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by b-kennedy0** [comment]
Hey @aldenc, Thanks for reporting this. This should be fixed in the next commit :)
