### ISSUE TITLE
[Bug]: Editing a link to an event

### ISSUE THREAD

**Issue by paumanduch** [openresearchcalendar/openresearchcalendar.github.io#109]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### What happened? / Describe the bug

I wanted to update the link to the following event:
ReproducibiliTea Bochum / Ruhr University Bochum [EN] - Tuesday, 22 October 2024.
The old link does not work - https://osf.io/b4k7m
And I wanted to add a new link - https://osf.io/fcbw7 
I tried to update both the section with the link, and the event description.
However, the old link still appears in the calendar. 

### Environment (if relevant)

```Markdown
- OS:
- Browser:
- Version:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by b-kennedy0** [comment]
@paumanduch Thanks for letting us know. We'll look into it!

**Comment by b-kennedy0** [comment]
@paumanduch 
Thanks for letting us know about this error. There was an issue with how the automation compared the old event description with the updated event description. It now correctly compares and identifies the change to the URL, forcing the calendar to update. 

I have updated the 6 entries for 'ReproducibiliTea Bochum / Ruhr University Bochum [EN]' and corrected the link to the one you provided.

**Comment by paumanduch** [comment]
Thank you very much for your help!
And thank you for this wonderful project!
