### ISSUE TITLE
[FEATURE] Embedded calendar code reads "List of events for 2013"

### ISSUE THREAD

**Issue by cassgvp** [openresearchcalendar/openresearchcalendar.github.io#11]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by b-kennedy0** [comment]
It appears this was simply some extra text added before the iframe embed, not an artefact of embedding. (Referenced pull request: https://github.com/cassgvp/WIN-Open-Neuroimaging-Community/pull/14#issue-486721407 )
