### ISSUE TITLE
[BUG] Incorrect date format in some short links

### ISSUE THREAD

**Issue by b-kennedy0** [openresearchcalendar/openresearchcalendar.github.io#28]
**Describe the bug**
On some bit.ly links tweeted, the date format was mixed to the US format. The link would display calendar page for 2/11 instead of 11/2. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Find tweet with easily confused date (e.g. one that can feasibly be switched between US/UK format)
2. Click on short bit.ly link to view in calendar.
3. View as wrong date

**Expected behaviour**
Expect to be taken to the correct event date. 

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: NA
 - Browser NA
 - Version NA

**Smartphone (please complete the following information):**
 - Device: NA
 - OS: NA
 - Browser NA
 - Version NA

**Additional context**
This was observed in only some tweets, particularly those with feasibly switchable dates, e.g. 11/02 could be switched to 02/11

**Comment by b-kennedy0** [comment]
**INVESTIGATION:** Integromat investigation showed that the issue was likely to do with the way the Bit.ly module parsed the date from the form entry. 

**FIX:** Data now comes from the Google Calendar module and is parsed in the following format to create the long URL:
![Screenshot 2020-10-26 at 12 09 15](https://user-images.githubusercontent.com/42816209/97170816-3b1fe500-1784-11eb-9301-f95817cc102b.png)
![Screenshot 2020-10-26 at 12 09 28](https://user-images.githubusercontent.com/42816209/97170824-3d823f00-1784-11eb-804d-b87eb2fdef89.png)

Fix closes issue #28

**Comment by cassgvp** [comment]
Tweets with wrong calendar link have been replied to in thread with a new link to the correct date in the calendar. 

See [calendar push sheet](https://docs.google.com/spreadsheets/d/1QnsALwDwHk4HJQGj0Sc19uJ5sLmmQDS3xUWMXW0Uh9o/edit?usp=sharing) tab "DateFormatFix" for how the corrected links were created and tweets found 😊  (columns T-AA).

Note this bug only became an issue when we added the "View this event in our calendar" link, so only events added after 23rd September 2020 could potentially have been effected.
