### ISSUE TITLE
Improve the clarity for adding events to the calendar

### ISSUE THREAD

**Issue by EstherPlomp** [openresearchcalendar/openresearchcalendar.github.io#30]
I had some questions/comments about how to add events. We should probably clarify better how to do this on the https://openresearchcalendar.github.io/ webpage: 

- add a button on the top for "add events" with a link to the google form
- add an "add event" section to the page that explains briefly that the events have to be added in British time and that we need an (estimation) of the start and end date in order to be able to add it to the calendar. 

Cheers, Esther

**Comment by b-kennedy0** [comment]
Added "Add Events" button to: 

1. Main page: https://github.com/openresearchcalendar/openresearchcalendar.github.io/commit/6acef309d1f2107ccb1f4308fb458612803cd607
2. Calendar page: https://github.com/openresearchcalendar/openresearchcalendar.github.io/commit/4dd58595e5f31d5c3e8569afa44cda438bb3fb4c

**Comment by b-kennedy0** [comment]
Need to:
- Add "How to add event(s)" section to index.md

**Comment by b-kennedy0** [comment]
Added in the relevant details to homepage, see: https://github.com/openresearchcalendar/openresearchcalendar.github.io/commit/b31c69f7a0fd857c169762cb67cd5a9f80595927

Closes issue
