### ISSUE TITLE
[BUG] Zenodo author information overwritten in new releases

### ISSUE THREAD

**Issue by cassgvp** [openresearchcalendar/openresearchcalendar.github.io#33]
A new release of this repo triggers a new version (and doi) in zenodo through GitHub integration. This is as expected. However the API on captures limited author information based on the metadata available in the repo. This omits those who have not contributed directly to the repo, any ORCID or affiliation information, and author order. 

FIX:
Copy the zenodo metadata created for an earlier release into a .json file in this repository, as described here: https://github.com/zenodo/zenodo/issues/1421

**Comment by cassgvp** [comment]
Metadata has been copied from here: https://zenodo.org/account/settings/github/repository/openresearchcalendar/openresearchcalendar.github.io#

Saved as .zenodo.json in commit 791d289a4fc644c7ae8123444ef74d3eb075ad13. 

Still need to test whether the version field will be overwritten with a new release, or if we should remove the field and let zenodo attempt to create the correct metadata incorporating what is already in the file. Doesn't seem to be a way of validating the .json in advance, as described here: https://github.com/zenodo/zenodo/issues/1606

**Comment by b-kennedy0** [comment]
We could potentially justify a new minor release as a result of the overhaul of the new tweet process that I updated (https://github.com/openresearchcalendar/openresearchcalendar.github.io/issues/21#issuecomment-732388223). Perhaps V1.3 ? What do you think

**Comment by cassgvp** [comment]
Up to you @b-kennedy0. I'm sure there are suggestions around when to release updates, but I'm not fussed either way :). 

Unless you we're thinking about running this release to test the zenodo integration? I might be misunderstanding.

**Comment by b-kennedy0** [comment]
Yeah I was thinking just to test the new Zenodo settings

**Comment by cassgvp** [comment]
That makes sense :). Can we add it as a non-urgent to-do and I'll get to it later?

**Comment by b-kennedy0** [comment]
No problem - added under `not_urgent` here: https://github.com/openresearchcalendar/openresearchcalendar.github.io/issues/35

**Comment by b-kennedy0** [comment]
Fixed in https://github.com/openresearchcalendar/openresearchcalendar.github.io/releases/tag/v2.0.1  by #64 
Closes #35
