### ISSUE TITLE
[BUG] "Date conflict issue"

### ISSUE THREAD

**Issue by anetapiekut** [openresearchcalendar/openresearchcalendar.github.io#41]
**Describe the bug**
Cannot save the event as it says that the end date is before the start date, which is not.

**Expected behaviour**
I wanted to add and save the event.

**Screenshots**
![image](https://user-images.githubusercontent.com/54583087/109634460-29d75280-7b41-11eb-88cb-99f31b7fb36e.png)

**Desktop:**
Please complete the following information if relevant, delete if not.
 - OS: Windows 
 - Browser: Chrome
 - Version: Version 88.0.4324.190

**Comment by b-kennedy0** [comment]
Thank you for bringing this to our attention - it seems to be an error with our logic checking. I have made some changes which *should* fix the issue. Thanks again

**Comment by b-kennedy0** [comment]
@anetapiekut - Could you please refresh the webpage and then try adding your event again. Thank you

**Comment by anetapiekut** [comment]
Thanks. I reloaded a refreshed a couple of times and now have: 
![image](https://user-images.githubusercontent.com/54583087/109651119-07036900-7b56-11eb-8a08-029953797778.png)

**Comment by anetapiekut** [comment]
But the dates conflict is resolved now.

**Comment by EstherPlomp** [comment]
Thanks @anetapiekut! @b-kennedy0, I just tried to add an event and I get the same error as @anetapiekut screenshotted above! Should we reopen the issue or open a new issue?

**Comment by b-kennedy0** [comment]
Thank you both @anetapiekut and @EstherPlomp - It looks as though the "Form outdated" error may be due to your browser caching an older version. Could you restart the browser and try it again.

**Comment by anetapiekut** [comment]
Indeed, it works now - thanks!

**Comment by b-kennedy0** [comment]
Great!!
