### ISSUE TITLE
University of Reading event 9th June

### ISSUE THREAD

**Issue by robertd17** [openresearchcalendar/openresearchcalendar.github.io#54]
Hello, I just listed an event University of Reading Open Research Award for 9th June, it should be from 13:00 to 15:30 UK time not 12:00 to 14:30. I thought I had to select time as UTC+1 to account for British Summer Time. Could you correct this please?
Thank you

Robert Darby

**Comment by b-kennedy0** [comment]
Hi @robertd17 - I've updated the details, the calendar will auto-refresh within the next 5 minutes and you should see the correct timings on the event 😊  (https://calendar.google.com/calendar/embed?src=openresearchcalendar@gmail.com&mode=day&dates=20210609/20210609)

**Comment by robertd17** [comment]
Hi Bradley

That's great - many thanks for sorting this out!

Best wishes

Robert


Dr Robert Darby | Research Data Manager | University of Reading

T: +44 (0)118 378 6161 | E: ***@***.***

http://www.reading.ac.uk/res-research-data-management.aspx

I am working from home and can be contacted on the above phone number and by Teams



Open Research Handbook: https://libguides.reading.ac.uk/open-research

[cid:3d13a6cc-96ac-4642-a495-f39077bd76e4]
UoR REDCap: https://www.reading.ac.uk/en/research-services/research-data-management/managing-your-data/uor-redcap
________________________________
