### ISSUE TITLE
Event email: events from June/July are listed together 

### ISSUE THREAD

**Issue by EstherPlomp** [openresearchcalendar/openresearchcalendar.github.io#55]
**Describe the bug**
In the Open Research Calendar email update the events from June/July are listed together: for example, an event on the 12th of July is listed in between two from June: 

•	Thank you, next: the future of research assessment (Online) - 09 **Jun** 2021 - Event Link
•	Alex Holcombe: Redressing imbalances in the kind of research that gets done and who gets credit for it [Swiss RN / AFC Lab Talk Series] (Online) - 12 **Jul** 2021 - Event Link
•	Japan open science summit (JOSS) 2021 (Online) - 14 **Jun** 2021 - Event Link

**To Reproduce**
Check the email update

**Expected behaviour**
It would be great if we could have a header with the first month and another header with the second month and have the events then listed chronologically.

**Comment by b-kennedy0** [comment]
That is odd! I'll take a look inside Integromat and see if there's an option I haven't ticked about "sorting" the dates!

**Comment by b-kennedy0** [comment]
![image](https://user-images.githubusercontent.com/42816209/120329883-3146fd00-c2e4-11eb-9968-f7ea9a7788f4.png)
