### ISSUE TITLE
edition of submission or preview before submitting

### ISSUE THREAD

**Issue by MalikaIhle** [openresearchcalendar/openresearchcalendar.github.io#60]
how to *edit* a submission for a new event?

can a preview of the tweet be implemented?
or a log in for that event so it can be edited after submission?

**Comment by b-kennedy0** [comment]
Hi @MalikaIhle, Thank you so much for the suggestion. The team and I will have a think about ways that we might implement this. 

The Tweet Preview should be fairly easy to implement. Editing of event details will be a bit more technically involved but will think about the best way to do that 😄

**Comment by b-kennedy0** [comment]
@MalikaIhle - You should now be able to find a new tab in the 'Calendar' menu called 'Edit Event' 😄

**Comment by MalikaIhle** [comment]
Excellent!

**Comment by cassgvp** [comment]
Woo hoo! Thank you @b-kennedy0 and @MalikaIhle!
