### ISSUE TITLE
Summer times

### ISSUE THREAD

**Issue by MalikaIhle** [openresearchcalendar/openresearchcalendar.github.io#62]
the list of time zones doesn't provide summer times, so I was wondering which to pick for BST:
UTC(+00) London or UTC (+1.00) Paris. 
I picked the first because we are in the UK and thought it would be less confusing but in fact we currently are in UTC +1...
anyway, the time will be on the registration page, but just thought I'd mention - though I'm sure you are aware...

**Comment by b-kennedy0** [comment]
I'm a little confused as to how Google handles summer time change! 

Can I check, you submitted the event with UTC+0 and it has been entered into the calendar for 3-4pm (which is the same time as the Eventbrite page), but technically you might have thought to enter it as UTC+1 given the fact we are in summer time? And then presumably this would enter the event into the calendar one hour early?

**Comment by MalikaIhle** [comment]
you are correct - so it seems it does convert to the correct time in the background (if summer time is involved) when choosing the right city. It's probably what most people would do anyway. But because I plan a lot of international meetings, I painfully know we currently are in UTC +1 in the UK, and the EU currently in UTC +0.
if it does the conversion well, then perhaps just saying somewhere to pick the city time zone even if on summer time, is enough.

**Comment by b-kennedy0** [comment]
Great suggestion! I will add that into the Help Text for that field. Thank you 😄

**Comment by b-kennedy0** [comment]
![Screenshot 2021-06-09 at 16 49 04](https://user-images.githubusercontent.com/42816209/121387984-02afce80-c943-11eb-8a70-b06b4822bbce.png)
![Screenshot 2021-06-09 at 16 49 11](https://user-images.githubusercontent.com/42816209/121388038-09d6dc80-c943-11eb-8a87-055ab9300037.png)
