### ISSUE TITLE
[BUG] November newsletter: december section is off

### ISSUE THREAD

**Issue by EstherPlomp** [openresearchcalendar/openresearchcalendar.github.io#66]
**Describe the bug**
The November newsletter does have one event listed for December, but it is taking place in November and none of the other events that are on the calendar for December are listed. 

**To Reproduce**
Check the November newsletter and scroll down to December section.

**Expected behaviour**
Find out what happened and perhaps send out a new version of the newsletter? If the events from November are correctly listed it might not be needed.

**Comment by b-kennedy0** [comment]
Hi @EstherPlomp - yes this certainly looks wrong doesn't it! I've check the calendar and we do have events in December so I'm not sure why our Integromat routine hasn't picked those out, even more curiously is why it's chosen that one November event as a "December" event! *confused face*

I will try to take a look at this today, if I manage to figure it out, we may resend the newsletter. Other option is to post our error on Twitter and say that it should be corrected for the 1st Dec email. Got to walk a careful line of not spamming inboxes and keeping our Intergromat "operations" low.

**Comment by b-kennedy0** [comment]
Investigation update: It appears to be an issue with date formatting between Integromat and Google Sheets. We store dates in UK format DD/MM/YYYY and when being processed at some point they are being read as MM/DD/YYYY - meaning that some dates are left out (those between 1st and 12th of the month) and they are being interpreted as a different month. 

I've reached out to Integromat directly for some support on this.

**Comment by b-kennedy0** [comment]
Feedback from Integromat:
---
Hello there Brad.

At first, let me thank you for getting in touch with us and for your interest in using Integromat.

I have inspected the scenario that you are referring to and if you want to process only the rows that have this month in the date field, I would suggest setting the search module to basically list all the available rows (no filter in the module) and then use Integromat filter as it's shown in the following screenshot:
![unnamed](https://user-images.githubusercontent.com/42816209/143006511-8745d6a9-b2db-4730-bdcb-5bab22775846.png)
![unnamed](https://user-images.githubusercontent.com/42816209/143006527-38d4225a-3903-4a6a-9414-b6f570e23c44.png)

---

This seems to have fixed the issue when I run a test. 

I will post an update on Twitter asap.

@EstherPlomp
