### ISSUE TITLE
donations don't work

### ISSUE THREAD

**Issue by researchtool** [openresearchcalendar/openresearchcalendar.github.io#67]
Going through the donation process, I can see the list of previous donations. I can access the form and fill it out. After submitting the form I receive a "500 Internal Server Error."

Tested with FF 94.0.2, MS Edge 96.

**Comment by b-kennedy0** [comment]
Thank you @researchtool for highlighting the bug. 

We'll take a look straight away!

**Comment by b-kennedy0** [comment]
Hi @researchtool I'm sorry you experienced some issues with the donation process. Investigating has shown that programming on our side seems to be working and that it was potentially a short-term issue experienced by a 3rd party (Either Tripetto or Monzo, but neither seem to have reported any issues!). 

We have checked the process across devices and internet connections for the last few hours and it seems to be working. Please could you check it now to see if it works for you?

**Comment by researchtool** [comment]
Hm. Still running into the server error (with both FF and Edge on Desktop and Android FF and Samsung Browser).

**Comment by b-kennedy0** [comment]
Thats very odd. Could you post a screenshot of the error here please? 

You should be getting re-directed to the following link:
`https://monzo.me/bradleykennedy5/X?d=Open%20Research%20Calendar`
where 'X' is the amount such as 5.00

**Comment by researchtool** [comment]
yep, there it i
![Screenshot 2021-11-25 140902](https://user-images.githubusercontent.com/5195357/143447880-dcbc499b-e53e-4457-9237-1567ee2be755.png)
![Screenshot 2021-11-25 141212](https://user-images.githubusercontent.com/5195357/143447890-c1f2da90-5731-4d81-926e-e8da72b50bcf.png)
s.

**Comment by researchtool** [comment]
It works if I copy your snippet and put in "5" instead of X. So there seems to be a problem with the redirection or encoding?
I could now make my donation, but I'll wait if I can still help to fix this.

**Comment by b-kennedy0** [comment]
Ah, that is super helpful to see. You are correct there is something going a bit funny with the amount. Thank you - will get onto fixing that encoding

**Comment by b-kennedy0** [comment]
Thanks for your help in diagnosing the issue @researchtool - We've now removed the troublesome "Amount" field from the form as it was not possible to get it correctly URL encoded. Should work correctly now. 
Thanks again !

**Comment by researchtool** [comment]
Happy to help. Gonna make my donation now :)
