### ISSUE TITLE
[FEATURE] Twitter handles in event description

### ISSUE THREAD

**Issue by b-kennedy0** [openresearchcalendar/openresearchcalendar.github.io#69]
@westwoodsam1 "Hey @OpenResearchCal peeps - is there a way to include twitter handles in the event so that they would be included in your auto-tweets? Would boost discoverability!"

**Comment by b-kennedy0** [comment]
Will update the New Event form to explain that tagging usernames (@username) in the Title will tag them in the Tweet

**Comment by b-kennedy0** [comment]
![Capture](https://user-images.githubusercontent.com/42816209/205108642-c8890f81-b2d2-4acc-86ee-375f5f2f3082.PNG)
Updated!

**Comment by EstherPlomp** [comment]
Whooo! Awesome 👍

**Comment by b-kennedy0** [comment]
The event title is mandatory, but including the @Username of somebody isn't. Just optional in case they would like to increase the discoverability of their event by tagging e.g. the speaker/organiser etc.

**Comment by b-kennedy0** [comment]
Perhaps we ought to add the word "Optional:" in front of the text explaining that you can tag usernames?

**Comment by EstherPlomp** [comment]
Sorry for the late response! But yes, the optional part is grand. I even skipped over it for the past couple of events that I added so I think it shouldn't hamper anyone not adding events! :)
