### ISSUE TITLE
[FEATURE] Include link to event in tweet

### ISSUE THREAD

**Issue by cassgvp** [openresearchcalendar/openresearchcalendar.github.io#7]
**Is your feature request related to a problem? Please describe.**
Having to click through to the calendar then find the event advertised is annoying. 

**Describe the solution you'd like**
Include a link to the event (as supplied by the person who submitted it) in the tweet. Links might have to be shortened if they are too long for the tweet. 

**Describe alternatives you've considered**
Link to the actual event in our calendar. Requires event id information, which we are already collecting. 

**Additional context**

**Comment by b-kennedy0** [comment]
This should be possible. The only hesitation I have is that if the tweet content plus the link exceeds the character limit, integromat will throw an error and the tweet won't go out. The work-around to that would be to have a step in the process that automatically shortens every link before adding it to the tweet content. I'll explore the options!

**Comment by cassgvp** [comment]
Might be nice to actually point people to the event in our calendar, if we can get that to work? It would bring them to the calendar, which is good for us!

**Comment by b-kennedy0** [comment]
Explored options on Integromat. Added new bitly component before the Tweet component to create a short link using the Event ID given by the Google Script. 
![image](https://user-images.githubusercontent.com/42816209/92007469-ea6cac80-ed3d-11ea-89c9-6a8eee785ddf.png)
The Tweet content now includes direct link to event. For example:

> New Open Research Event 🎓📆 - Test event in Physical Place from 2/9/20 to 2/9/20. View this event in the calendar: https://t.co/IcFhV3Dewt

Happy to get further feedback on this. Closing issue for now.

**Comment by b-kennedy0** [comment]
Turns out this wasn't quite as easy as that. Linking to the individual event requires re-encoding the eventID back into Base64. Instead the link now takes you to the day-view of the start date of the particular event using the following code work-around: 
![image](https://user-images.githubusercontent.com/42816209/92012869-ed1ed000-ed44-11ea-9b07-a31dc2dd2efc.png)

**Comment by cassgvp** [comment]
Nice hack. I think the day is fine :). Integromat is the gift that keeps on giving!

**Comment by b-kennedy0** [comment]
REOPENING ISSUE - Need to continue to explore the "Add to Calendar" option to increase functionality of calendar events.

**Comment by b-kennedy0** [comment]
Direct event link now included in tweet, as well as day-view link. Only concern is that if the event title and/or location are rather long, it could surpass the Twitter character limits. Not sure how Integromat would respond, I imagine it would throw an error and then halt the process there.  
Tweet layout:
![image](https://user-images.githubusercontent.com/42816209/93536164-59522400-f940-11ea-8df8-c1b5a9db78b6.png)

Shall we trial this for now and see how it goes - **reopen the issue if we have problems with character limits.**
