### ISSUE TITLE
November Newsletter not sent

### ISSUE THREAD

**Issue by b-kennedy0** [openresearchcalendar/openresearchcalendar.github.io#76]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Contact Details

b.kennedy@chester.ac.uk

### What happened? / Describe the bug

Newsletter not sent on 1st Nov 22.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by EstherPlomp** [comment]
Shoot! I did not notice this but you're absolutely right :(

**Comment by b-kennedy0** [comment]
Well, this was an easy fix - the scenario on Make was not activated! During the sending in October, a cascading error prevented the run from finishing (https://openresearchcalendar.statuspage.io/incidents/qz7g1ybt3t5d), after a fix, the activation failed to save. 

It has been turned back on now and the next newsletter will be sent on December 1st. The November newsletter has been uploaded to Github (17628ddc7ee55fb233187ebbd1a139d47a8ecc3b) and can be found on the website (https://openresearchcalendar.org/email-newsletter/archive/22_11_November_Newsletter).
