### ISSUE TITLE
[BUG] Update "In [location]" tweet wording to be compatible for online events

### ISSUE THREAD

**Issue by cassgvp** [openresearchcalendar/openresearchcalendar.github.io#8]
**Describe the bug**
Tweets are formatted "[event name] in [location]". This doesn't work for "Online" locations. 

**To Reproduce**
1. Submit an event
2. Add the location as "online"

**Expected behavior**
The template text should be compatible with "online" location. For example with an in-person or online switch. 

**Screenshots**
https://twitter.com/OpenResearchCal/status/1274297208506994688?s=20 

**Desktop and mobile OS (please complete the following information):**
 - OS: all
 - Browser: all
 - Version: all

**Comment by b-kennedy0** [comment]
Explored our options in Integromat and I have added an if function that takes the lowercase, trimmed text of Location and evaluates if it contains the word "online". If it does the word inserted is "held" and if not, the word is "in". 

`New Open Research Event 🎓📆 - {{Event Title}} {{if(contains(trim(lower(Location)); "online") = true; "held"; "in")}}{{Location}} from {{Start Date}} to {{End Date}}. View this event in the calendar: {{Bitly Short-link}}`

This results in outputs such as: 

> New Open Research Event 🎓📆 - Test event in Physical Place from 2/9/20 to 2/9/20. View this event in the calendar: https://t.co/IcFhV3Dewt

> New Open Research Event 🎓📆 - Test event held Online from 2/9/20 to 2/9/20. View this event in the calendar: https://t.co/IcFhV3Dewt

Happy to receive further feedback on wording. For now, closing the issue.

**Comment by cassgvp** [comment]
Amazing, rapid work! Always impressed with the speed which you fix these things @b-kennedy0!

**Comment by b-kennedy0** [comment]
- Update to include "virtual" in logic

**Comment by b-kennedy0** [comment]
Far too difficult to incorporate "Virtual" into the logic as "held Virtual" still doesn't make sense in the Tweet. It would require further logic to change the location to "Online". It was easier to change the guidance when completing the new event form. As noted in the screenshot below, guidance has been added to the 'Location' field. 
![Capture](https://user-images.githubusercontent.com/42816209/94912887-39724280-04a0-11eb-93d2-20185b890d34.PNG)
