### ISSUE TITLE
[Bug]: Multiday events that span two months don't show in the newsletter

### ISSUE THREAD

**Issue by gavinscode** [openresearchcalendar/openresearchcalendar.github.io#86]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Contact Details

gavin.taylor.01@gmail.com

### What happened? / Describe the bug

The February 2023 newsletter didn't show two multiday events that started in February but finished in March.
These were the:
- Responsible Animal Research Course
- Open Research Week 2023

### Environment (if relevant)

```Markdown
Gmail inbox in Chrome
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by b-kennedy0** [comment]
Hello @gavinscode - Thank you for reporting this bug. It looks like it might be related to how our code searches for relevant events. I'll take a look and see if we can modify it.

**Comment by b-kennedy0** [comment]
So some good news and some bad news:

**Good news:** The code is already set up to handle events that start in one month and end in the next. We can see from the records that the 'Responsible Animal Research Course' was submitted to the ORC on _02/02/2023 10:11:57_. As the Newsletter conducts its search on the 1st day of the month at 9 am (Europe/London), that event was not in the database at the time of the search. 

**Bad news:** The event 'Open Research Week 2023' was submitted to the ORC on _7/12/2022 13:53:10_ so it *should* have made it into the newsletter. It seems that at some point between _Dec 29th 2022_ and _Dec 31st 2022_, the event was manually removed from our database (it looks like it was human error!). So the event exists on the calendar but not in our database. When the newsletter process ran, it searched our **database** and not the **calendar**, therefore, it did not find that event.

Thanks again for raising the bug report. It helps us to find errors like this and prevent them in the future.
